app_admin_byrd_product_mapping:
  resource: |
    alias: bitbag_sylius_byrd_shipping_export_plugin.byrd_product_mapping
    section: admin
    templates: "@BitBagByrdShippingExportPlugin/CrudUi"
    except: ['show']
    grid: bitbag_sylius_byrd_shipping_export__admin__byrd_product_mapping
    redirect: index
    permission: true
  type: sylius.resource

sylius_byrd_shipping_export_plugin_filter_byrd_products:
  path: /byrd_products
  methods: GET
  controller: sylius_byrd_shipping_export_plugin.controller.filter_byrd_products
